---

- name: Install
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  become: yes

- name: Install extensions
  command: "/usr/bin/code --install-extension {{ item }}"
  loop:
    - wholroyd.jinja
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode.cpptools
    - redhat.ansible
    - redhat.vscode-yaml
    - shd101wyy.markdown-preview-enhanced

- name: Install python packages for jupyter
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - ipykernel
    - bash_kernel
    - notebook
    - nbconvert
    - jupyter_contrib_nbextensions
  become: yes

- name: Install ipython bash kernel
  command: /usr/bin/python -m bash_kernel.install
  become: yes

- name: Install nbextension javacsript and css files
  command: /usr/local/bin/jupyter contrib nbextension install --system
  become: yes

- name: Install packages for jupyter pdf export
  apt:
    name: "{{ item }}"
  loop:
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-plain-generic
    - pandoc
  become: yes