---

- name: Install
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  become: yes

- name: Install extensions
  command: "/usr/bin/code --install-extension {{ item }}"
  loop:
    - wholroyd.jinja
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode.cpptools
    - redhat.ansible
    - redhat.vscode-yaml
    - shd101wyy.markdown-preview-enhanced

- name: Install python packages for jupyter
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - ipykernel
    - notebook
    - nbconvert
  become: yes

- name: Install packages for jupyter pdf export
  apt:
    name: "{{ item }}"
  loop:
    - texlive-xetex
    - texlive-fonts-recommended
    - texlive-plain-generic
  become: yes