---

- name: Install application
  package:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - chromium
    - libreoffice
    - network-manager-openvpn
    - python3-venv
    - seclists

- name: Configure git email
  git_config:
    name: user.email
    value: "carl@pekare.se"
    scope: global
 
- name: Configure git name 
  git_config:
    name: user.name
    value: "Carl Larsson"
    scope: global
