---

- name: Install
  package:
    name: docker.io
    state: present
  become: yes

- name: Give user access to daemon
  user:
    name: '{{ ansible_user_id }}'
    append: yes
    groups: docker
  become: yes
