---

- name: Ensure dependencies are installed
  package:
    name: gnupg2
    state: present
  become: yes

- name: Download and install
  apt:
    deb: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
  become: yes

- name: Enable ssh-agent
  blockinfile:
  path: "{{ ansible_env.HOME }}/.ssh/config"
    block: |
      Host *
        IdentityAgent ~/.1password/agent.sock
